# Copyright 2025-2026 Nemoto-lab, The University of Osaka
# email: rodolfo.allendes.prime@osaka-u.ac.jp
# email: nemoto.takahiro.prime@osaka-u.ac.jp

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---
import click, sys, traceback

import pandas as pd 
from pathlib import Path

@click.group()
def genotype():
  pass

@genotype.command()
@click.argument('inpath', type=click.Path(exists=True))
@click.argument('oupath', type=str)
@click.option('--force', is_flag=True, help='Override target file.')
def aggregate_pileup(inpath, oupath, force):
    """ Aggregate pileup files generated by cellSNP into a single DataFrame
    
    Arguments:

        INPATH: Path to the folder containing cellSNP output files. The folder
            should contain at least the following files: cellSNP.samples.tsv, 
            cellSNP.tag.AD.mtx, cellSNP.tag.DP.mtx, and cellSNP.tag.OTH.mtx.
        
        OUPATH: Path to the folder to store the aggregated pileup file.
    """
    # remove possible trailing slash
    inpath = str(inpath).rstrip('/') if len(str(inpath))>1 else str(inpath)
    oupath = oupath.rstrip('/') if len(oupath)>1 else oupath
    
    tgt = Path('{}/aggregated_pileup.pkl.gz'.format(oupath))
    # only regenerate if the file does not exist or if the regenerate flag is set
    if tgt.is_file() and not force:
      print('Aggregated pileup found at: {}'.format(tgt))
      return pd.read_pickle(tgt)

    # create output path directory if it does not exist
    outdir = Path(oupath)
    outdir.mkdir(parents=True, exist_ok=True)

    # load cell barcodes
    try:
      cells = pd.read_table('{}/cellSNP.samples.tsv'.format(inpath),
        comment='#', 
        header=None, 
        names=['bcode']
      )
      cells.index+=1
    except Exception as e:
      print('Error loading {}/cellSNP.samples.tsv'.format(inpath))
      print(traceback.format_exc())
      sys.exit(1)

    #load three different count matrices
    try:
      AD = pd.read_table('{}/cellSNP.tag.AD.mtx'.format(inpath),
        names=['SNP','Cell', 'AD'], index_col=(['SNP','Cell']),
        comment='%', header=0
      )
    except Exception as e:
      print('Error loading {}/cellSNP.tag.AD.mtx'.format(inpath))
      print(traceback.format_exc())
      sys.exit(1)
    try:
      DP = pd.read_table("{}/cellSNP.tag.DP.mtx".format(inpath),
        names=['SNP','Cell', 'DP'], index_col=(['SNP','Cell']),
        comment='%',header=0
      )
    except Exception as e:
      print('Error loading {}/cellSNP.tag.DP.mtx'.format(inpath))
      print(traceback.format_exc())
      sys.exit(1)
    try:
      OTH = pd.read_table("{}/cellSNP.tag.OTH.mtx".format(inpath),
        names=['SNP','Cell', 'OTH'], index_col=(['SNP','Cell']),
        comment='%',header=0
      )
    except Exception as e:
      print('Error loading {}/cellSNP.tag.OTH.mtx'.format(inpath))
      print(traceback.format_exc())
      sys.exit(1)

    # combine everything into a genotype file
    ag = pd.concat([AD,DP,OTH],axis=1).fillna(0.)
    
    # add cell barcodes 
    snpidx = ag.index.get_level_values('SNP')
    celidx = ag.index.get_level_values('Cell')
    ag['bcode']= cells.loc[celidx,'bcode'].values

    # save the resulting file
    print('Saving aggregated pileup to {}'.format(tgt))
    ag.to_pickle('{}'.format(tgt), compression='gzip')
    return ag 

def call_aggregate_pileup(inpath, oupath, force):
    """ Python API wrapper for :func:`aggregate_pileup`.

    Args:
        inpath: Path to the folder containing cellSNP output files. The folder
            should contain at least the following files: cellSNP.samples.tsv, 
            cellSNP.tag.AD.mtx, cellSNP.tag.DP.mtx, and cellSNP.tag.OTH.mtx.
        oupath: Path to the folder to store the aggregated pileup file.
        force: If `True`, override any existing output file.
    """
    return aggregate_pileup.callback(
      inpath=inpath, 
      oupath=oupath,
      force=force
      )

if __name__ == '__main__':
  genotype()