# Copyright 2025-2026 Nemoto-lab, The University of Osaka
# email: rodolfo.allendes.prime@osaka-u.ac.jp
# email: nemoto.takahiro.prime@osaka-u.ac.jp

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---

import click
import traceback
import math
import ast

from pathlib import Path
import pandas as pd
import numpy as np

from . import genotype
from . import plotting

@click.group()
def snpic():
  pass

@snpic.command()
@click.argument('inpath', type=click.Path(exists=True))
@click.argument('oupath', type=str)
@click.option('--force', is_flag=True, help='Override target file.')
def calculate_snpic(inpath, oupath, force):
    """Computes the SNP Information Content (SNP-IC) for each cell based on the
    pileup output of cellSNP and saves the per-cell counts to a compressed
    pickle file. Results are stored in ``snpic_counts.pkl.gz`` under OUPATH.
    
    Arguments:

        INPATH: Path to the folder containing cellSNP output files. Must
        contain ``cellSNP.samples.tsv``, ``cellSNP.tag.AD.mtx``,
        ``cellSNP.tag.DP.mtx``, and ``cellSNP.tag.OTH.mtx``.

        OUPATH: Path where the SNP-IC counts will be saved
    """
    # only regenerate if the file does not exist or if the force flag is set
    tgt = Path('{}/snpic_counts.pkl.gz'.format(oupath))
    if tgt.is_file() and not force:
      print('SNP-IC counts found at: {}'.format(tgt))
      return tgt

    # calculate or fetch the aggregated pileup information
    ag = genotype.call_aggregate_pileup(
      inpath=inpath,
      oupath=oupath,
      force=force
    )
    # calculate the aggregate information for all SNPs in a given cell
    ag.reset_index(drop=True, inplace=True)
    ag = ag.groupby(by='bcode').sum()
    ag['DPOTH'] = ag.DP+ag.OTH

    # save the resulting file
    print('Saving SNP-IC counts to: {}'.format(tgt))
    ag.to_pickle(tgt, compression='gzip')
    return tgt

def call_calculate_snpic(inpath, oupath, force):
    """Python API wrapper for :func:`calculate_snpic`.

    Args:
        inpath: Path to the folder containing cellSNP output files. Must
            contain ``cellSNP.samples.tsv``, ``cellSNP.tag.AD.mtx``,
            ``cellSNP.tag.DP.mtx``, and ``cellSNP.tag.OTH.mtx``.
        oupath: Path where the SNP-IC counts will be saved.
        force: If ``True``, overrides any existing output file.

    Returns:
        pathlib.Path: Path to ``snpic_counts.pkl.gz``.
    """
    return calculate_snpic.callback(
      inpath=inpath,
      oupath=oupath,
      force=force
    )

@snpic.command()
@click.argument('agfile', type=str)
@click.argument('oupath', type=str)
@click.option('--force', is_flag=True, help='Override target file.')
def generate_histogram(agfile, oupath, force):
    """ Generate a histogram of SNP-IC values from a SNP-IC counts file. Returns 
    the name of the file where the histogram DataFrame is stored.

    Arguments:

        AGFILE: Path to the SNP-IC counts file (pkl.gz) generated by calculate_snpic.
        
        OUPATH: Path to the folder where to store the histogram file.
    """
    tgt = Path('{}/snpic_histogram.pkl'.format(oupath))
    if tgt.is_file() and not force:
      print('SNP-IC histogram file found at: {}'.format(tgt))
      return tgt

    # load the SNP-IC counts file
    print('Loading SNP-IC counts from: {}'.format(agfile))
    agdf = pd.read_pickle(agfile)

    m = math.ceil(agdf.DPOTH.max())
    nb = 100 if m>100 else m # fix the maximum number of bins
    step = m//nb
    bin_edges = np.arange(start=0,stop=m+step, step=step) # make sure the bins have int-edges
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2 # midpoint of each bin
    
    bin_counts, _ = np.histogram(
      agdf.DPOTH.dropna().values,
      bins=bin_edges,
    )
    
    hist = pd.DataFrame({
      'centers': bin_centers,
      'counts': bin_counts
      })

    # save the resulting file
    print('Saving SNP-IC histogram to: {}'.format(tgt))
    Path(oupath).mkdir(parents=True, exist_ok=True)
    hist.to_pickle(tgt)
    
    # return the file where the histogram is stored
    return tgt 

def call_generate_histogram(agfile, oupath, force):
    """ Python API wrapper for :func:`generate_histogram`.

    Args:
        agfile: Path to the SNP-IC counts file (pkl.gz) generated by calculate_snpic.
        oupath: Path to the folder where to store the histogram file.
        force: If ``True``, overrides any existing output file.

    Returns:
        pathlib.Path: Path to the generated histogram file.
    """
    return generate_histogram.callback(
      agfile=agfile,
      oupath=oupath,
      force=force
    )

@snpic.command()
@click.argument('histofile', type=str)
@click.argument('output', type=str)
@click.option('--force', is_flag=True, help='Override target file.')
def save_snpic_plot(histofile, output, force):
    """ Save a SNP-IC histogram plot.
    
    Arguments:

        HISTOFILE: Path to the SNP-IC histogram file (pkl) generated by generate_histogram.
        
        OUTPUT: Path to the output file where to save the figure (should end with .html).
    """
    tgt = Path(output)
    if tgt.is_file() and not force:
      print('Figure file {} already exists, skipping...'.format(tgt))
      return
    
    # generate the figure
    fig = plotting.generate_snpic_plot(histofile)
    # save the figure to the output file
    plotting.save_plot(
      figure=fig,
      output=output,
      force=force
    )

def call_save_snpic_plot(histofile, output, force):
    """ Python API wrapper for :func:`save_snpic_plot`.

    Args:
        histofile: Path to the SNP-IC histogram file (pkl) generated by generate_histogram.
        output: Path to the output file where to save the figure (should end with .html).
        force: If ``True``, overrides any existing output file.

    Returns:
        pathlib.Path: Path to the generated figure file.
    """
    return save_snpic_plot.callback(
        histofile=histofile,
        output=output,
        force=force
  )

@snpic.command()
@click.argument('barfile', type=click.Path(exists=True, dir_okay=False))
@click.argument('agfile', type=click.Path(exists=True, dir_okay=False))
@click.argument('oupath', type=str)
@click.argument('n')
@click.option('--seed', type=int, default=None, help='Seed used for reproducible results.')
@click.option('--force', is_flag=True, help='Override target files')
def estimate_donor_assignment(barfile, agfile, oupath, n, seed, force):
    """Estimate donor assignment for each barcode based on SNP-IC values.

    Arguments:

        BARCODES: Path to the list of barcodes to be assigned
    
        AGFILE: Path to the SNP-IC counts file (pkl.gz) generated by calculate_snpic.
        
        OUPATH: Path to the folder where to store the resulting bars file
    
        N: Number of donors (ex: 5) or List of probabilities (ex: [0.1,0.3,0.4,0.2] - no spaces).
    """
    tgt = Path(f"{oupath}/snpic_bars.pkl")
    if tgt.is_file() and not force:
      print(f"SNP-IC donor estimation bars file found at: {tgt}. Skipping...")
      return tgt

    # read the file and store as a list
    bcodes = list(pd.read_table(barfile, names=['bcode']).bcode)
    
    # provide seed for deterministic output
    rng = np.random.default_rng(seed) 
    
    # depending on options provided we proceed slightly different with respect to 
    # the probabilities used for the multimodal distribution used for the donor
    # assignation
    n = ast.literal_eval(str(n))
    assert type(n) in [int, list], "--n should be either an integer or a list of probabilities"
    if type(n) == int:
      print('Using --n equally distributed donors for barcode/donor mapping estimation')
      # number of cells per donor based on equal probabilities
      cpd = rng.multinomial(len(bcodes), [1/n]*n)
    else:
      print('Using --n probabilities for barcode/donor mapping estimation')
      # number of cells per donor
      cpd = rng.multinomial(len(bcodes), n)
    print(cpd)
    
    # the cummulative sum, i.e indices in the bcodes list associated to each donor
    cpdc = np.cumsum(cpd) 

    # randomly shuffle the cells
    rng.shuffle(bcodes)
    # load the barcodes and their associated SNP-IC values
    snpic = pd.read_pickle(agfile)
    snpicbcode = set(snpic.index) #list of bcodes with SNP-IC value available

    snpic['donor'] = -1
    snpic['correct'] = False

    # determine the barcodes associated to each donor and how many of them 
    # can be considered correctly assigned based on the SNP-IC>50 threshold
    j=0
    for idx,i in enumerate(cpdc):
      sel = bcodes[j:i] # selected barcodes
      # index(barcodes) != index(snp-ic barcodes)
      isec = snpicbcode.intersection(set(sel))
      # save donor and correctly assigned
      
      snpic.loc[list(isec),'donor'] = idx
      # print(snpic.loc[list(isec),'donor'])

      snpic.loc[(snpic.donor==idx) & (snpic.DPOTH >= 50), 'correct'] = True
      # print(snpic.loc[(snpic.donor==idx) & (snpic.DPOTH >= 50), 'correct'])
      j = i

    # save the resulting file
    print(f"Saving donor estimation bars to: {tgt}")
    snpic = snpic[['donor', 'correct']]
    Path(oupath).mkdir(parents=True, exist_ok=True)
    snpic.to_pickle(tgt)
    
    # return the file where the bars are stored
    return tgt

def call_estimate_donor_assignment(barfile, agfile, oupath, n, seed=None, force=False):
    """Python API wrapper for :func:`estimate_donor_assignment`
  
    Args:
        barfile (str): Path to the list of barcodes to be assigned
        agfile (str): Path to the SNP-IC counts file (pkl.gz) generated by calculate_snpic
        oupath (str): Path to the folder where to store the resulting bars file
        n (int or list): Number of donors or list of probabilities
        seed (int, optional): Seed used for reproducible results
        force (bool): Override target files

    Returns:
        Path: Path to the generated bars file
    """
    return estimate_donor_assignment.callback(
      barfile=barfile,
      agfile=agfile,
      oupath=oupath,
      n=n,
      # pval=pval,
      seed=seed,
      force=force
    )

@snpic.command()
@click.argument('barfile', type=str)
@click.argument('output', type=str)
@click.option('--force', is_flag=True, help='Override target file.')
def save_donor_estimation_plot(barfile, output, force):
    """ Save a donor estimation plot

    Arguments:

        BARFILE: Path to the bar definitions file (pkl) generated by the 
            estimate_donor_assignment function
        OUTPUT: Path to the output file where to save the figure
    """
    tgt = Path(output)
    if tgt.is_file() and not force:
      print(f"Figure file {tgt} already exists, skipping...")
      return 
    
    # generate the figure
    fig = plotting.generate_donor_distribution_plot(barfile)
    # save the figure to the output file
    plotting.save_plot(
      figure=fig,
      output=output,
      force=force
    )

def call_save_donor_estimation_plot(barfile, output, force):
    """Python API wrapper for :func:`save_donor_estimation_plot`
  
    Args:
        barfile (str): Path to the bar definitions file (pkl) generated by the estimate_donor_assignment function
        output (str): Path to the output file where to save the figure
        force (bool): Override target file
    """
    return save_donor_estimation_plot.callback(
      barfile=barfile,
      output=output,
      force=force
    )


@snpic.command()
@click.argument('inpath')
@click.argument('oupath')
@click.option('--force', is_flag=True, help='Override target files.')
def run_all(inpath, oupath, force):
    """Full SNP-IC calculation pipeline.
  
    Arguments:
    
        INPATH: Path to the folder containing cellSNP output files. The folder
            should contain at least the following files: cellSNP.samples.tsv, 
            cellSNP.tag.AD.mtx, cellSNP.tag.DP.mtx, and cellSNP.tag.OTH.mtx.
        
        OUPATH: Path to the output folder where all results will be stored. 
    """
    # step 1: calculate the SNP-IC counts
    snpicfile = call_calculate_snpic(
      inpath=inpath,
      oupath=oupath,
      force=force
    )
    
    # step 2: generate the SNP-IC histogram
    histofile = call_generate_histogram(
      agfile=snpicfile,
      oupath=oupath,
      force=force
    )

    # step 3: generate the SNP-IC plot
    fig = plotting.generate_snpic_plot(histofile)
    plotting.save_plot(
      figure=fig,
      output='{}/snpic_figure.html'.format(oupath),
      force=force
    )

def call_run_all(inpath, oupath, force):
    """Python API wrapper for :func:`run_all`.
    
    Args:
        inpath: Path to the folder containing cellSNP output files. The folder
            should contain at least the following files: cellSNP.samples.tsv, 
            cellSNP.tag.AD.mtx, cellSNP.tag.DP.mtx, and cellSNP.tag.OTH.mtx.
        oupath: Path to the output folder where all results will be stored.
        force: If ``True``, overrides any existing output files.
    """
    return run_all.callback(
      inpath=inpath,
      oupath=oupath,
      force=force
    )

if __name__ == '__main__':
  snpic()